name = "ddeabm"
author = "Jacob Williams"
copyright  = "Copyright (c) 2014-2021, Jacob Williams"
license = "BSD-3"
description = "Modern Fortran Implementation of the DDEABM Adams-Bashforth Algorithm"
homepage = "https://github.com/jacobwilliams/ddeabm"
keywords = ["ODE", "Ordinary Differential Equations", "ODE solver", "Adams-Bashforth-Moulton", "root finding", "DEPAC", "SLATEC"]

[dependencies]
roots-fortran = { git = "https://github.com/jacobwilliams/roots-fortran", rev = "1.1.0" }

[dev-dependencies]
pyplot-fortran = { git = "https://github.com/jacobwilliams/pyplot-fortran", rev = "3.2.0" }

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[library]
source-dir = "src"

[install]
library = true

