ddeabm_with_event_wrapper_vec – ddeabm
ddeabm_with_event_wrapper_vec Subroutine
Jacob Williams
197 statements
Source File
private subroutine ddeabm_with_event_wrapper_vec(me, t, y, tmax, tstop, idid, gval, integration_mode, tstep, continue)
Wrapper routine for ddeabm, with event finding for multiple functions. It will integrate until any g(t,x)=0 or t=tmax (whichever comes first). Note that a root at the initial time is ignored (user should check for this manually)
If starting a new problem, must first call me%first_call().
See also
ddeabm_with_event_wrapper -- for scalar g function
Note
Currently not using the recommended tols if idid=-2.
Type Bound
ddeabm_with_event_class_vec
Arguments
Type Intent Optional Attributes Name
class(ddeabm_with_event_class_vec), intent(inout) :: me
real(kind=wp), intent(inout) :: t
real(kind=wp), intent(inout), dimension(me%neq) :: y
real(kind=wp), intent(in) :: tmax
max time at which a solution is desired. (if root not located, it will integrate to tmax)
real(kind=wp), intent(in), optional :: tstop
for some problems it may not be permissible to integrate past a point tstop because a discontinuity occurs there or the solution or its derivative is not defined beyond tstop. when you have declared a tstop point (see info(4)), you have told the code not to integrate past tstop. in this case any tmax beyond tstop is invalid input. [not used if not present]
integer, intent(out) :: idid
indicator reporting what the code did. you must monitor this integer variable to decide what action to take next. idid>1000 means a root was found for the (idid-1000)th g function. See ddeabm for other values.
real(kind=wp), intent(out), dimension(:) :: gval
value of the event functions g(t,x) at the final time t
integer, intent(in), optional :: integration_mode
Step mode: 1 - normal integration from t to tout, no reporting [default]. 2 - normal integration from t to tout, report each step.
real(kind=wp), intent(in), optional :: tstep
Fixed time step to use for reporting and evaluation of event function. If not present, then default integrator steps are used.
logical, intent(in), optional :: continue
to continue after a previous event location. This option can be used after a previous call to this routine has found an event, to continue integration to the next event without having to restart the integration. It will not report the initial point (which would have been reported as the last point of the previous call).
Calls
Source Code
   subroutine ddeabm_with_event_wrapper_vec(me, t, y, tmax, tstop, idid, gval, integration_mode, tstep, continue)
      implicit none
      class(ddeabm_with_event_class_vec), intent(inout) :: me
      real(wp), intent(inout)                         :: t
      real(wp), dimension(me%neq), intent(inout)       :: y
      real(wp), intent(in)                            :: tmax !! max time at which a solution is desired.
                                                              !! (if root not located, it will integrate to `tmax`)
      real(wp), intent(in), optional                   :: tstop !! for some problems it may not be permissible to integrate
                                                                !! past a point `tstop` because a discontinuity occurs there
                                                                !! or the solution or its derivative is not defined beyond
                                                                !! `tstop`.  when you have declared a `tstop` point (see `info(4)`),
                                                                !! you have told the code not to integrate past `tstop`.
                                                                !! in this case any `tmax` beyond `tstop` is invalid input.
                                                                !! [not used if not present]
      integer, intent(out)                            :: idid !! indicator reporting what the code did.
                                                              !! you must monitor this integer variable to
                                                              !! decide what action to take next.
                                                              !! `idid>1000` means a root was found for the
                                                              !! (`idid-1000`)th `g` function.
                                                              !! See [[ddeabm]] for other values.
      real(wp), dimension(:), intent(out)              :: gval !! value of the event functions `g(t,x)` at the final time `t`
      integer, intent(in), optional :: integration_mode !! Step mode:
                                                        !! *1* - normal integration from `t` to `tout`,
                                                        !!  no reporting [default].
                                                        !! *2* - normal integration from `t` to `tout`,
                                                        !!  report each step.
      real(wp), intent(in), optional :: tstep !! Fixed time step to use for reporting and
                                              !! evaluation of event function. If not present,
                                              !! then default integrator steps are used.
      logical, intent(in), optional :: continue !! to continue after a previous event location.
                                                !! This option can be used after a previous call to this routine
                                                !! has found an event, to continue integration to the next event
                                                !! without having to restart the integration. It will not report
                                                !! the initial point (which would have been reported as the last
                                                !! point of the previous call).
      ! local variables:
      real(wp), dimension(:),allocatable :: g1         !! value of event function at `t1`
      real(wp), dimension(:),allocatable :: g2         !! value of event function at `t2`
      logical, dimension(:),allocatable :: root_found  !! if a root was found
      real(wp), dimension(:),allocatable :: y1  !! initial state in an interval
      real(wp), dimension(:),allocatable :: y2  !! final state in an interval
      real(wp), dimension(:),allocatable :: yc  !! interpolated state at `tc`
      real(wp) :: t1              !! initial time of an interval
      real(wp) :: t2              !! final time of an interval
      real(wp) :: tzero           !! time where an event occurs in `[t1,t2]`
      integer :: iflag            !! `root_scalar` status flag
      logical :: first            !! flag for the first step
      integer :: mode             !! local copy of integration_mode
      integer :: i                !! counter
      integer :: ig               !! `gfunc` to compute
      real(wp) :: tprev           !! earliest time of root when there are
                                  !! multiple roots on the integration
                                  !! step interval
      logical :: forward          !! if `tmax>=t`
      logical :: fixed_step       !! if using the fixed step size `tstep`
      logical :: last             !! for fixed step size: the last step
      real(wp) :: dt              !! for fixed step size: actual signed time step
      real(wp) :: direction       !! direction of integration for
                                  !! fixed step size: `+1: dt>=0`, `-1: dt<0`
      logical :: continuing       !! local copy of optional `continue` argument
      real(wp) :: first_dt        !! for fixed step size: the `dt` for the
                                  !! first step  (can differ from `dt` if
                                  !! continuing from a previous event solve)
      character(len=10) :: istr   !! for integer to string conversion
      integer :: istat            !! for write statement `iostat`
      ! work arrays:
      allocate(g1(me%n_g_eqns))
      allocate(g2(me%n_g_eqns))
      allocate(root_found(me%n_g_eqns))
      allocate(y1(me%neq))
      allocate(y2(me%neq))
      allocate(yc(me%neq))
      ! optional inputs:
      if (present(integration_mode)) then
         mode = integration_mode
      else
         mode = 1  !default
      end if
      if (present(continue)) then
         ! if there has not yet been a successful
         ! step yet, then proceed as normal without
         ! continuing. Otherwise, enable continue mode.
         continuing = (continue .and. allocated(me%x_saved))
      else
         continuing = .false.
      end if
      !if this is a "forward" (dt>=0) integration
      forward = tmax >= t
      ! if we are reporting the output at a fixed step size:
      fixed_step = present(tstep)
      if (fixed_step) then
         direction = sign(1.0_wp, tmax - t)
         dt = direction*abs(tstep)
         first_dt = dt
         last = .false.
      end if
      if (continuing) then
         ! if continuing, then we reset the t,y inputs
         ! to the values from the last successful step
         ! (note than an event may have been found in the
         ! last call, so the input values are not correct)
         if (fixed_step) then
            ! we need the first step to be from the
            ! last reported point, not the last
            ! successful step:
            first_dt = (t + dt) - me%t_saved
            ! make sure not a 0 dt or in the wrong direction:
            if (first_dt == 0.0_wp .or. sign(1.0_wp, first_dt) /= sign(1.0_wp, dt)) first_dt = dt
            !
            ! WARNING: this can happen if the previous step was
            ! larger than t+dt.... in that case, first_dt will be
            ! the wrong sign (we cannot change the direction of integration)...
            ! what needs to be done is the interp
            ! routine should be called to fill in the rest of the
            ! points until we get past the last step.  TDB !
            !
            !... we would also need to check those points for roots...
            !
         end if
         t = me%t_saved
         y = me%x_saved
         me%info(1) = 1   ! necessary? (does not seem to matter)
      end if
      !check for invalid inputs:
      if (mode /= 1 .and. mode /= 2) then
         call report_error('ddeabm_with_event_wrapper_vec', &
                           'integration_mode must be 1 or 2.', 0, 0)
         idid = -33
         return
      end if
      if ((mode == 2) .and. (.not. associated(me%report))) then
         call report_error('ddeabm_with_event_wrapper_vec', &
                           'REPORT procedure must be associated for integration_mode=2.', 0, 0)
         idid = -33
         return
      end if
      !make sure the event function was set:
      if (.not. associated(me%gfunc)) then
         call report_error('ddeabm_with_event_wrapper_vec', &
                           'the event function GFUNC has not been associated.', 0, 0)
         idid = -33
         return
      end if
      !set info array:
      !info(1) is set when ddeabm_new_problem is called
      !info(2)
      if (me%scalar_tols) then
         me%info(2) = 0
      else
         me%info(2) = 1
      end if
      !info(3)
      if (fixed_step) then
         me%info(3) = 0  !return after integrating to the specified (fixed step) time
      else
         me%info(3) = 1  !intermediate output mode: return after each default step
      end if
      !info(4)
      if (present(tstop)) then
         me%info(4) = 1
         me%tstop = tstop
      else
         me%info(4) = 0
         me%tstop = 0.0_wp !not used
      end if
      !make a copy of the tols, since the routine might change them:
      me%rtol_tmp = me%rtol
      me%atol_tmp = me%atol
      !evaluate the event function at the initial point:
      first = .true.  !to avoid catching a root at the initial time
      t1 = t
      y1 = y
      call me%gfunc(t1, y1, g1)  ! compute all the g functions
      if (mode == 2 .and. .not. continuing) call me%report(t, y)  !initial point
      do
         if (fixed_step) then
            ! take one step to t2 and return
            if (first) then
               t2 = t + first_dt
            else
               t2 = t + dt
            end if
            last = direction*(tmax - t2) <= 0.0_wp  ! if last point
            if (last) t2 = tmax  ! adjust last time step if necessary
         else
            t2 = tmax  ! take a step in the direction of tmax and return
         end if
         !call the lower-level routine:
         call me%ddeabm(neq=me%neq, &
                        t=t, &
                        y=y, &
                        tout=t2, &
                        info=me%info, &
                        rtol=me%rtol_tmp, &
                        atol=me%atol_tmp, &
                        idid=idid)
         ! if there was an integration error (see ddeabm or idid codes):
         if (idid < 0) exit
         !if there was a user-triggered error:
         if (me%error) then
            idid = -1000
            exit
         end if
         !save the last successful step in the class:
         me%t_saved = t
         me%x_saved = y
         !evaluate all event functions at new point:
         t2 = t
         y2 = y
         call me%gfunc(t2, y2, g2)
         if (first .and. any(abs(g1) <= me%tol)) then
            ! ignore a root at the initial time (first point)
            ! (or if continuing integration from a previous root)
            ! warning: is this check always sufficient? or
            !          is it possible for zeroin to have
            !          converged to a root outside this tol?
         else if (any(g1*g2 <= 0.0_wp)) then ! change in sign of the event function
            ! find the one(s) with sign change:
            do i = 1, me%n_g_eqns
               root_found(i) = g1(i)*g2(i) <= 0.0_wp
            end do
            ! the user bracket function can impose
            ! additional constraints on the root, so
            ! we check that now if it was associated:
            if (associated(me%bracket)) then
               do i = 1, me%n_g_eqns
                  if (root_found(i)) then
                     root_found(i) = me%bracket(i, t1, t2, y1, y2, g1(i), g2(i))
                  end if
               end do
            end if
            if (any(root_found)) then
               ! root somewhere on [t1,t2]
               ! have to check all the functions where this is true,
               ! and select the one with the earlier root.
               ! initialize. goal is to find the earliest
               ! one (in direction of integration):
               if (forward) then
                  tprev = huge(1.0_wp)
               else
                  tprev = -huge(1.0_wp)
               end if
               idid = -2000 ! if no root is found
               do i = 1, me%n_g_eqns
                  if (.not. root_found(i)) cycle
                  ! Note: it's possible that zeroing in on one root
                  ! will cause another earlier root to be detected?
                  ! This is not currently handled. Only the ones identified
                  ! by the normal stepping process are considered.
                  ! this func has a root somewhere on [t1,t2]
                  ig = i  ! when calling zeroin, we only need to compute
                  ! the ith function
                  ! call the root finder:
                  call root_scalar(root_method_brent, &
                                   fun=zeroin_func, &
                                   ax=t1, &
                                   bx=t2, &
                                   rtol=me%tol(i), &
                                   ftol=me%tol(i), &
                                   xzero=tzero, &
                                   fzero=gval(i), &
                                   iflag=iflag, &
                                   fax=g1(i), &
                                   fbx=g2(i))
                  if (iflag == 0) then !root found at tzero
                     if ((forward .and. tzero < tprev) .or. (.not. forward .and. tzero > tprev)) then
                        ! this is an earlier root so use it
                        idid = 1000 + ig  ! root found
                        t = tzero
                        y = yc
                        tprev = t
                     end if
                  else
                     ! unlikely to occur since zeroin is
                     ! "guaranteed" to converge, but just in case:
                     write (istr, '(I10)', iostat=istat) i
                     call report_error('ddeabm_with_event_wrapper_vec', &
                                       'Error locating root for function '// &
                                       trim(adjustl(istr)), 0, 0)
                     ! do not reset idid in case another root was found
                  end if
               end do
               ! if no errors, report the root if necessary, then return:
               if (idid > 0) then
                  if (mode == 2) call me%report(t, y)
                  call me%gfunc(t, y, gval) ! compute all funcs for output
               else
                  call report_error('ddeabm_with_event_wrapper_vec', &
                                    'Error locating root.', 0, 0)
               end if
               return
            end if
         end if
         ! report this point:
         if (mode == 2) call me%report(t, y)
         ! integration is finished (see ddeabm or idid codes):
         if (fixed_step) then
            if (last) return
         else
            if (idid == 2 .or. idid == 3) return
         end if
         ! set up for next step:
         first = .false.
         g1 = g2
         t1 = t2
         y1 = y2
      end do
   contains
      function zeroin_func(tc) result(g)
            !! evaluate the `ig`th `g` function at `tc`
            !! using interpolation ([[dintp]]).
         implicit none
         real(wp), intent(in) :: tc  !! current time
         real(wp)             :: g   !! value of event function
         real(wp), dimension(me%n_g_eqns) :: gtmp
         ! interpolate to get the state at tc:
         call me%interpolate(tc, yc)
         ! user defined event function:
         ! [only compute the one we need]
         call me%gfunc(tc, yc, gtmp, ig)
         g = gtmp(ig)
      end function zeroin_func
   end subroutine ddeabm_with_event_wrapper_vec
Call graph
ddeabm_with_event_wrapper_vec calls info, ddeabm, report_error, report, root_scalar
ddeabm calls report_error, ddes
ddes calls report_error, dintp, dsteps
dsteps calls dhstrt
dhstrt calls dhvnrm