dhvnrm – ddeabm
dhvnrm Function
Jacob Williams
7/1/2014
7 statements
Source File
private function dhvnrm(v, n) result(m)
Compute the maximum norm of the first n elements of vector v. Replacement for the original SLATEC routine.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: v
integer, intent(in) :: n
Return Value real(kind=wp)
Called by
Source Code
   function dhvnrm(v, n) result(m)
      implicit none
      real(wp)                         :: m
      integer, intent(in)               :: n
      real(wp), dimension(:), intent(in) :: v
      m = maxval(abs(v(1:n)))
   end function dhvnrm
Call graph
dhstrt calls dhvnrm
dsteps calls dhstrt
ddes calls dsteps
ddeabm calls ddes
ddeabm_with_event_wrapper calls ddeabm
ddeabm_with_event_wrapper_vec calls ddeabm
ddeabm_wrapper calls ddeabm