report_error – ddeabm
report_error Subroutine
Jacob Williams
8 statements
Source File
private subroutine report_error(subrou, messg, nerr, level)
Report an error message.
Replacement for original XERMSG error message printing routine. This one just prints the message to the console.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: subrou
subroutine where error occurred
character(len=*), intent(in) :: messg
error message
integer, intent(in) :: nerr
error code
integer, intent(in) :: level
[Not used here] * -1: warning message (once), * 0: warning message, * 1: recoverable error, * 2: fatal error
Called by
Source Code
   subroutine report_error(subrou, messg, nerr, level)
      implicit none
      character(len=*), intent(in) :: subrou  !! subroutine where error occurred
      character(len=*), intent(in) :: messg   !! error message
      integer, intent(in)          :: nerr    !! error code
      integer, intent(in)          :: level   !! [Not used here]
                                              !!  * -1: warning message (once),
                                              !!  * 0: warning message,
                                              !!  * 1: recoverable error,
                                              !!  * 2: fatal error
      write (error_unit, '(A)') 'Error in '//trim(subrou)//': '//trim(messg)
   end subroutine report_error
Call graph
ddeabm calls report_error, ddes
ddeabm_with_event_wrapper calls report_error, ddeabm
ddeabm_with_event_wrapper_vec calls report_error, ddeabm
ddeabm_wrapper calls report_error, ddeabm
ddes calls report_error